name: Example - Deploy a Gen2 Cloud Function using gcloud
on:
  workflow_dispatch:

jobs:
  example:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # actions/checkout MUST come before auth
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          repository: GoogleCloudPlatform/python-docs-samples # Taken from https://cloud.google.com/functions/docs/create-deploy-gcloud#functions-prepare-environment-python

      - name: 'Authenticate to GCP as Infrastructure SA for deployment'
        uses: 'google-github-actions/auth@v1'
        with:
          export_environment_variables: true
          project_id : ${{ vars.PROJECT_ID }}
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.INFRA_SA_EMAIL }} # Use your Infrastructure SA to manage resources

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Deploy Gen2 Cloud Function'
        id: deploy
        env:
          FUNCTION_NAME: 'python-http-function'
          REGION: 'europe-west3'
          WORKLOAD_SA_EMAIL: ${{ vars.WORKLOAD_SA_EMAIL }} # Why not use this direct in the script? See https://docs.github.com/en/enterprise-cloud@latest/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
        run: |
          set -e
          
          gcloud functions deploy "${FUNCTION_NAME}" \
          --entry-point="hello_get" \
          --gen2 \
          --region="${REGION}" \
          --runtime="python311" \
          --service-account="${WORKLOAD_SA_EMAIL}" \
          --source="functions/helloworld" \
          --trigger-http
          
          url=$(gcloud functions describe "${FUNCTION_NAME}" --gen2 --region="${REGION}" --format="value(serviceConfig.uri)")
          echo "url=${url}" >> "${GITHUB_OUTPUT}"

      # Only needed to get an ID token to simulate an authenticated curl call.
      # Not needed for deployment.
      - name: 'Authenticate to GCP as workload SA for invocation'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'id_token' # <--
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.WORKLOAD_SA_EMAIL }} # Use your Workload SA to interact with resources
          id_token_audience: ${{ steps.deploy.outputs.url }}
          id_token_include_email: true

      - name: 'Poke Cloud Run'
        run: 'curl -H "Authorization: Bearer ${{ steps.auth.outputs.id_token }}" "${{ steps.deploy.outputs.url }}"'